{{- if and .Values.rbac.create (not .Values.rbac.clusterRole) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-viewer" (include "external-dns.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "external-dns.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "external-dns.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
