apiVersion: v2
name: bedrock
description: INITEQ's collection of base k8s tools.

keywords:
  - ingress-nginx
  - cert-manager
  - external-dns
  - kube2iam
  - kubernetes-dashboard
  - heapster

version: 0.6.1

dependencies:
  - name: ingress-nginx
    version: "3.34.0"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled

  - name: kube2iam
    version: "2.6.0"
    repository: https://jtblin.github.io/kube2iam/
    condition: kube2iam.enabled

  - name: external-dns
    version: "3.4.2"
    repository: https://charts.bitnami.com/bitnami
    condition: external-dns.enabled

  - name: cert-manager
    version: "1.0.2"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled

  # - name: kubernetes-dashboard
  #   version: "1.0.2"
  #   repository: "https://charts.jetstack.io"
  #   condition: kubernetes-dashboard.enabled

maintainers:
  - name: INITEQ
    email: info@initeq.net
    url: https://initeq.net
