{{- if and (index .Values "cert-manager" "enabled") (index .Values "cert-manager" "clusterIssuer" "create") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ index .Values "cert-manager" "clusterIssuer" "name" }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook": "post-upgrade"
spec:
  acme:
    # The ACME server URL
    server: {{ index .Values "cert-manager" "clusterIssuer" "server" }}
    # Email address used for ACME registration
    email: {{ index .Values "cert-manager" "clusterIssuer" "email" }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ index .Values "cert-manager" "clusterIssuer" "name" }}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
