{{- if and (index .Values "cert-manager" "enabled") (index .Values "cert-manager" "clusterIssuer" "create") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ index .Values "cert-manager" "clusterIssuer" "name" }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  acme:
    # The ACME server URL
    server: {{ index .Values "cert-manager" "clusterIssuer" "server" }}
    # Email address used for ACME registration
    email: {{ index .Values "cert-manager" "clusterIssuer" "email" }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ index .Values "cert-manager" "clusterIssuer" "name" }}
    # Enable the HTTP-01 or DNS01 challenge provider
    # NOTE: if using DNS you need to give the certmanager pod permission to make
    # entries in your DNS (eg. route53). This can be accomplished by using "extraEnv"
    # and injecting the AWS credentials as environment variables.
    # Another option if using kube2iam is to add an annotation with the correct IAM role.
    solvers:
    {{ toYaml (index .Values "cert-manager" "clusterIssuer" "solvers") | nindent 4}}
{{- end }}
