apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aws-ecr-helper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-ecr-helper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-ecr-helper
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "aws-ecr-helper.serviceAccountName" . }}
