apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "aws-ecr-helper.fullname" . }}-{{ now | htmlDate }}
  labels:
    {{- include "aws-ecr-helper.labels" . | nindent 4 }}
spec:
  backoffLimit: 4
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "aws-ecr-helper.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aws-ecr-helper.serviceAccountName" . }}
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
        - name: aws-ecr-helper
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - "/usr/local/bin/refresh_credentials.sh"
          env:
            - name: AWS_ACCOUNT
              value: "{{ .Values.awsAccount }}"
            - name: AWS_REGION
              value: "{{ .Values.awsRegion }}"
            - name: TARGET_NAMESPACES
              value: "{{ .Values.targetNamespaces }}"
