name: Charts
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch...
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Determine Chart Repo
        id: helm_chart
        run: |
          if [[ ${GITHUB_REF} == 'refs/heads/master' ]]; then
              echo "::set-output name=scp_location::charts@initeq.net:/var/www/charts/"
              echo "::set-output name=repo_url::https://charts.initeq.net"
          else
              echo "::set-output name=scp_location::charts@initeq.net/var/www/dev-charts/${GITHUB_REF}/"
              echo "::set-output name=repo_url::https://charts.dev.initeq.net/${GITHUB_REF}"
          fi
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Build Chart Packages
        uses: "docker://cloudposse/build-harness:0.37.0"
        with:
          args: "-C incubator all"
        env:
          HELM_CHART_REPO_URL: ${{ steps.helm_chart.outputs.repo_url }}

      - name: Generate Index
        uses: "docker://cloudposse/build-harness:0.37.0"
        with:
          args: "-C packages all"
        env:
          HELM_CHART_REPO_URL: ${{ steps.helm_chart.outputs.repo_url }}
